; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\adnan.masood\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
